### PR TITLE
Enable rendering rich text content in posts

### PR DESCRIPTION
**Pull request by hasali19**
This needs to be tested on ios - from what I've read online, behaviour of the webview may have some differences between platforms.

### CODE REVIEW

**Comment by hasali19** [comment]
Could you also check if the link opens in an external browser or in the webview itself?

As for the style we could probably inject some CSS into the webview.

**Comment by pranavmangal** [comment]
> Could you also check if the link opens in an external browser or in the webview itself?

It opens in an external browser (Safari on iOS).

> As for the style we could probably inject some CSS into the webview.

Yeah I think that should work.

**Comment by hasali19** [comment]
Could try setting it to the sans-serif font and see how it looks. You can modify the html document in UpdateData.js.

**Comment by pranavmangal** [comment]
I think it looks pretty good with sans-serif (I used the default one).

IMG_6339

**Comment by hasali19** [comment]
Yeah I think that's more or less how it looks on my phone.

image

**Pull request merged**
